### ISSUE TITLE
Appears that various is*_utf8() functions will have their interfaces change.

### ISSUE THREAD

**Issue by sgtchains** [creaktive/Text-SpeedyFx#3]
FYI;

Running Perl v5.28.1 and receiving the following warnings;

In SpeedyFx.xs, line 353, starting in Perl v5.30, isWORDCHAR_utf8() will require an additional parameter.  Avoid this message by converting to use isWORDCHAR_utf8_safe().
In SpeedyFx.xs, line 354, starting in Perl v5.30, toLOWER_utf8() will require an additional parameter.  Avoid this message by converting to use toLOWER_utf8_safe().

**Comment by creaktive** [comment]
Thanks for reporting! Will release the fix to CPAN soon :)

**Comment by creaktive** [comment]
...and it is out! https://metacpan.org/release/SYP/Text-SpeedyFx-0.013
